
import React, { useState, useEffect, useRef } from 'react';
import { AnalysisResult } from '../types.ts';

interface Props {
  onUpload: (file: File) => void;
  loading: boolean;
  result: AnalysisResult | null;
  error: string | null;
  selectedFile: File | null;
}

const AnalyzerView: React.FC<Props> = ({ onUpload, loading, result, error, selectedFile }) => {
  const [viewTab, setViewTab] = useState<'dashboard' | 'preview'>('dashboard');
  const [audioUrl, setAudioUrl] = useState<string | null>(null);

  useEffect(() => {
    if (selectedFile) {
      const url = URL.createObjectURL(selectedFile);
      setAudioUrl(url);
      return () => URL.revokeObjectURL(url);
    }
  }, [selectedFile]);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      onUpload(e.target.files[0]);
    }
  };

  const getMarkdown = () => {
    if (!result) return '';
    return `
# Audio Analysis Report
Generated by ScribeAI - ${new Date().toLocaleDateString()}

## 1. Executive Summary
${result.executiveSummary}

## 2. Action Items
${result.actionItems.length > 0 
  ? result.actionItems.map(item => `- [ ] **${item.task}** (Assignee: ${item.assignee})`).join('\n')
  : "_No specific action items identified._"}

## 3. Sentiment Analysis
- **Tone:** ${result.sentiment.label}
- **Confidence:** ${(result.sentiment.score * 100).toFixed(0)}%
- **Analysis:** ${result.sentiment.explanation}

## 4. Transcript Appendix
> ${result.transcription}
    `.trim();
  };

  const downloadMarkdown = () => {
    const content = getMarkdown();
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ScribeAI_Report_${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(getMarkdown());
    alert('Markdown report copied to clipboard!');
  };

  return (
    <div className="space-y-10">
      <div className="text-center max-w-3xl mx-auto space-y-4">
        <h1 className="text-4xl font-extrabold text-slate-900 sm:text-5xl tracking-tight leading-tight">
          Intelligent Audio <span className="text-indigo-600">Transcription</span>
        </h1>
        <p className="text-xl text-slate-500 font-medium">
          Upload any audio file to generate executive summaries, action items, 
          and professional markdown reports in seconds.
        </p>
      </div>

      <div className="glass-card rounded-[2rem] shadow-2xl shadow-indigo-100 overflow-hidden">
        <div className="p-10 text-center">
          <div 
            className={`group relative flex flex-col items-center justify-center border-2 border-dashed border-slate-200 rounded-3xl p-16 transition-all duration-300 ${loading ? 'opacity-60 cursor-not-allowed' : 'hover:border-indigo-400 hover:bg-indigo-50/30 cursor-pointer'}`}
            onClick={() => !loading && document.getElementById('audio-upload')?.click()}
          >
            <input
              type="file"
              accept="audio/*"
              onChange={handleFileChange}
              className="hidden"
              id="audio-upload"
              disabled={loading}
            />
            
            <div className={`w-20 h-20 rounded-2xl bg-indigo-50 flex items-center justify-center mb-6 group-hover:scale-110 transition-transform duration-300 ${loading ? 'animate-pulse' : ''}`}>
              <i className={`fas ${loading ? 'fa-spinner fa-spin text-indigo-600' : 'fa-cloud-arrow-up text-indigo-500'} text-3xl`}></i>
            </div>

            <h3 className="text-xl font-bold text-slate-800 mb-2">
              {loading ? 'Processing Intelligence...' : 'Drop your audio here'}
            </h3>
            <p className="text-slate-400 max-w-sm">
              Supporting MP3, WAV, M4A, and AAC. Files are analyzed securely using Gemini 3 Flash.
            </p>
            
            {!loading && (
              <button className="mt-8 px-8 py-3 bg-indigo-600 text-white font-bold rounded-xl shadow-lg shadow-indigo-200 hover:bg-indigo-700 hover:shadow-indigo-300 transition-all">
                Select Local File
              </button>
            )}
          </div>

          {audioUrl && !loading && (
            <div className="mt-8 p-6 bg-slate-50 rounded-2xl border border-slate-100 flex flex-col items-center animate-in">
              <span className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-4">File Preview</span>
              <audio controls src={audioUrl} className="w-full max-w-md outline-none" />
              <p className="mt-2 text-sm text-slate-500 italic">"{selectedFile?.name}"</p>
            </div>
          )}
        </div>
      </div>

      {error && (
        <div className="bg-red-50 border border-red-100 p-6 rounded-2xl flex items-center gap-4 animate-in">
          <div className="w-12 h-12 bg-red-100 rounded-xl flex items-center justify-center text-red-600">
            <i className="fas fa-circle-exclamation text-xl"></i>
          </div>
          <div>
            <h4 className="font-bold text-red-900">Analysis Failed</h4>
            <p className="text-sm text-red-700">{error}</p>
          </div>
        </div>
      )}

      {result && (
        <div className="space-y-8 animate-in">
          <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
            <div className="flex bg-slate-100 p-1.5 rounded-2xl border border-slate-200">
              <button
                onClick={() => setViewTab('dashboard')}
                className={`px-6 py-2.5 rounded-xl text-sm font-bold transition-all ${
                  viewTab === 'dashboard' ? 'bg-white text-indigo-600 shadow-md' : 'text-slate-500'
                }`}
              >
                Analytics Dashboard
              </button>
              <button
                onClick={() => setViewTab('preview')}
                className={`px-6 py-2.5 rounded-xl text-sm font-bold transition-all ${
                  viewTab === 'preview' ? 'bg-white text-indigo-600 shadow-md' : 'text-slate-500'
                }`}
              >
                Report Preview
              </button>
            </div>
            
            <div className="flex gap-3 w-full md:w-auto">
                <button
                onClick={downloadMarkdown}
                className="flex-1 md:flex-none px-6 py-3 bg-indigo-600 text-white font-bold rounded-xl shadow-xl shadow-indigo-100 hover:bg-indigo-700 transition-all flex items-center justify-center gap-2"
                >
                <i className="fas fa-download"></i>
                Export .MD
                </button>
                <button
                onClick={copyToClipboard}
                className="flex-1 md:flex-none px-6 py-3 bg-slate-900 text-white font-bold rounded-xl shadow-xl shadow-slate-200 hover:bg-black transition-all flex items-center justify-center gap-2"
                >
                <i className="fas fa-copy"></i>
                Copy
                </button>
            </div>
          </div>

          {viewTab === 'dashboard' ? (
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
              <div className="lg:col-span-2 space-y-8">
                <div className="bg-white p-8 rounded-3xl border border-slate-100 shadow-sm">
                  <div className="flex items-center gap-3 mb-6">
                    <div className="w-10 h-10 bg-indigo-50 rounded-xl flex items-center justify-center text-indigo-600">
                      <i className="fas fa-align-left"></i>
                    </div>
                    <h3 className="text-xl font-bold text-slate-900">Executive Summary</h3>
                  </div>
                  <p className="text-slate-600 leading-relaxed text-lg italic font-medium">
                    "{result.executiveSummary}"
                  </p>
                </div>

                <div className="bg-white p-8 rounded-3xl border border-slate-100 shadow-sm">
                  <div className="flex items-center gap-3 mb-6">
                    <div className="w-10 h-10 bg-emerald-50 rounded-xl flex items-center justify-center text-emerald-600">
                      <i className="fas fa-list-check"></i>
                    </div>
                    <h3 className="text-xl font-bold text-slate-900">Key Action Items</h3>
                  </div>
                  <div className="grid gap-4">
                    {result.actionItems.length > 0 ? result.actionItems.map((item, i) => (
                      <div key={i} className="group flex items-center gap-4 p-5 bg-slate-50 rounded-2xl hover:bg-white hover:shadow-md border border-transparent hover:border-slate-100 transition-all">
                        <div className="w-6 h-6 rounded-full border-2 border-emerald-300 flex items-center justify-center group-hover:bg-emerald-500 group-hover:border-emerald-500 transition-colors">
                          <i className="fas fa-check text-[10px] text-white opacity-0 group-hover:opacity-100"></i>
                        </div>
                        <div className="flex-grow">
                          <p className="font-bold text-slate-800">{item.task}</p>
                          <p className="text-xs text-slate-400 uppercase tracking-wider font-bold mt-1">
                            Assignee: <span className="text-indigo-500">{item.assignee}</span>
                          </p>
                        </div>
                      </div>
                    )) : <p className="text-slate-400 italic">No tasks identified.</p>}
                  </div>
                </div>

                <div className="bg-white p-8 rounded-3xl border border-slate-100 shadow-sm">
                  <div className="flex items-center gap-3 mb-6">
                    <div className="w-10 h-10 bg-slate-100 rounded-xl flex items-center justify-center text-slate-600">
                      <i className="fas fa-paragraph"></i>
                    </div>
                    <h3 className="text-xl font-bold text-slate-900">Raw Transcript</h3>
                  </div>
                  <div className="max-h-80 overflow-y-auto pr-4 text-slate-500 leading-relaxed font-medium">
                    {result.transcription}
                  </div>
                </div>
              </div>

              <div className="space-y-8">
                <div className="bg-white p-8 rounded-3xl border border-slate-100 shadow-sm sticky top-32">
                  <div className="flex items-center gap-3 mb-8">
                    <div className="w-10 h-10 bg-rose-50 rounded-xl flex items-center justify-center text-rose-600">
                      <i className="fas fa-face-smile"></i>
                    </div>
                    <h3 className="text-xl font-bold text-slate-900">Mood Analysis</h3>
                  </div>
                  
                  <div className="flex flex-col items-center py-6">
                    <div className={`text-4xl font-black mb-4 tracking-tighter ${
                      result.sentiment.label === 'Positive' ? 'text-emerald-600' :
                      result.sentiment.label === 'Negative' ? 'text-rose-600' : 'text-amber-600'
                    }`}>
                      {result.sentiment.label}
                    </div>
                    
                    <div className="w-full h-4 bg-slate-100 rounded-full overflow-hidden mb-6 flex">
                       <div 
                        className={`h-full transition-all duration-1000 ${
                          result.sentiment.label === 'Positive' ? 'bg-emerald-500' :
                          result.sentiment.label === 'Negative' ? 'bg-rose-500' : 'bg-amber-500'
                        }`}
                        style={{ width: `${result.sentiment.score * 100}%` }}
                       />
                    </div>
                    
                    <p className="text-center text-sm text-slate-500 leading-relaxed px-4">
                      {result.sentiment.explanation}
                    </p>
                  </div>
                </div>
              </div>
            </div>
          ) : (
            <div className="bg-white p-10 rounded-[2rem] shadow-2xl overflow-hidden min-h-[600px] border border-slate-100">
              <div className="max-w-4xl mx-auto prose prose-indigo">
                <div className="flex items-center justify-between mb-8 pb-4 border-b border-slate-100">
                  <div className="flex items-center gap-3">
                    <div className="w-3 h-3 rounded-full bg-rose-400"></div>
                    <div className="w-3 h-3 rounded-full bg-amber-400"></div>
                    <div className="w-3 h-3 rounded-full bg-emerald-400"></div>
                  </div>
                  <span className="text-slate-400 font-mono text-xs uppercase tracking-widest">ScribeAI_Report.md</span>
                </div>
                <div className="text-slate-800 font-mono text-sm overflow-x-auto whitespace-pre-wrap leading-relaxed bg-slate-50 p-6 rounded-xl border border-slate-100">
                  {getMarkdown()}
                </div>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
};

export default AnalyzerView;
